server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api-server?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1qaz2wsx3edc
    username: root
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒
    timeout: 6000
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      min-idle: 0    # 连接池中的最小空闲连接
file:
  upload:
    path: C:\Users\LIN\Desktop\api-server\src\main\resources\static\wav
tts:
  url: https://10.10.10.170:8443